---
off_title: "Autoclickers partie II – Clickpocalypse !"
title: "A"
date: 2017-02-05
tags: [javascript, incremental-games, intelligence-artificielle]
uscripts: ['js/incremental-games-autoclicker.js']
---



Seconde partie de ma série d'articles sur les _autoclickers_ avec un exemple :
CLICKPOCALYPSE 2.

++++
<!-- more -->
++++


include::source/_includes/autoclicker-toc.adoc[]

Dans le link:/2017/01/31/incremental-games-autoclicker/[premier article] de
cette série nous avons fait un prototype de boucle qui exécutait une simple
action.

Pour http://minmaxia.com/c2/[Clickpocalypse 2], le jeu nous offre plein de
possibilités, mais comme le jeu doit être mis à jour à chaque action du joueur,
nous ne pouvons exécuter que l'une d'entre elles à chaque tour.

Notre algorithme va donc être séparé en deux parties : D'abord, décider l'action
à entreprendre selon certaines priorités. Ensuite, exécuter cette action.

Il ne s'agît pas ici de tricher, mais simplement de rendre le jeu encore plus
_idle_. Nous allons donc seulement implémenter l'achat automatique des
compétences des personnages, très utile puisque quand on « prestige », ceux-ci
commencent avec toujours plus de points de compétences ; et la récupération
automatique des récompenses : _farms_, niveaux d'ennemis, ventes d'objets et
bien entendu le _loot_ !


== Setup

J'ai développé cet autoclicker dans Chromium avec
https://tampermonkey.net/[Tampermonkey], disponible également pour Chrome et
Vivaldi. Il existe également pour Firefox mais je conseille plutôt
https://addons.mozilla.org/fr/firefox/addon/greasemonkey/[Greasemonkey].

Ces outils permettent d'ajouter automatiquement un ou plusieurs scripts sur une
page web, chargés automatiquement au démarrage de la page. Plus besoin de lancer
les scripts depuis la console comme on le faisait pour notre premier
autoclicker.

Cependant, ces scripts s'exécutent dans une _sandbox_, c'est à dire un contexte
javascript différent de celui de la page web. Il faut donc leur donner
explicitement l'accès à notre objet `window` afin de pouvoir interagir avec la
page. Cela se fait via `@grant unsafeWindow` dans le _header_ de notre script.
Ensuite, on déclare nos variables `window` et `document`, notre code aura l'air
plus « habituel » et surtout, on pourra le tester directement dans la console.

[source,javascript]
----
// ==UserScript==
// @name         Clickpocalypse 2 Autoclicker
// @grant        unsafeWindow
// ==/UserScript==
'use strict'

var window = unsafeWindow
var document = window.document
----


Attente du chargement
Récupération des liens & boutons
Lecture des points de compétence disponibles
Orchestration
