---
off_title: "Autoclickers partie II – Clickpocalypse !"
title: "A"
date: 2017-02-05
tags: [javascript, incremental-games, intelligence-artificielle]
uscripts: ['js/incremental-games-autoclicker.js']
---



Seconde partie de ma série d'articles sur les _autoclickers_ avec un exemple :
CLICKPOCALYPSE 2.

++++
<!-- more -->
++++


include::source/_includes/autoclicker-toc.adoc[]

Dans le link:/2017/01/31/incremental-games-autoclicker/[premier article] de
cette série nous avons fait un prototype de boucle qui exécutait une simple
action.

Pour http://minmaxia.com/c2/[Clickpocalypse 2], le jeu nous offre plein de
possibilités, mais comme le jeu doit être mis à jour à chaque action du joueur,
nous ne pouvons exécuter que l'une d'entre elles à chaque tour.

Notre algorithme va donc être séparé en deux parties : D'abord, décider l'action
à entreprendre selon certaines priorités. Ensuite, exécuter cette action.

Il ne s'agît pas ici de tricher, mais simplement de rendre le jeu encore plus
_idle_. Nous allons donc seulement implémenter l'achat automatique des
compétences des personnages, très utile puisque quand on « prestige », ceux-ci
commencent avec toujours plus de points de compétences ; et la récupération
automatique des récompenses : _farms_, niveaux d'ennemis, ventes d'objets et
bien entendu le _loot_ !


== Setup

J'ai développé cet autoclicker dans Chromium avec
https://tampermonkey.net/[Tampermonkey], disponible également pour Chrome et
Vivaldi. Il existe également pour Firefox mais je conseille plutôt
https://addons.mozilla.org/fr/firefox/addon/greasemonkey/[Greasemonkey].

Ces outils permettent d'ajouter automatiquement un ou plusieurs scripts sur une
page web, chargés automatiquement au démarrage de la page. Plus besoin de lancer
les scripts depuis la console comme on le faisait pour notre premier
autoclicker.

Cependant, ces scripts s'exécutent dans une _sandbox_, c'est à dire un contexte
javascript différent de celui de la page web. Il faut donc leur donner
explicitement l'accès à notre objet `window` afin de pouvoir interagir avec la
page. Cela se fait via `@grant unsafeWindow` dans le _header_ de notre script.
Ensuite, on déclare nos variables `window` et `document`, notre code aura l'air
plus « habituel » et surtout, on pourra le tester directement dans la console.

[source,javascript]
----
// ==UserScript==
// @name         Clickpocalypse 2 Autoclicker
// @grant        unsafeWindow
// ==/UserScript==
'use strict'

var window = unsafeWindow
var document = window.document
----

== Définir les actions de l'autoclicker

Il faut maitenant récupérer toutes les fonctions de clic que l'on souhaite
utiliser.

=== Afficher les onglets

Lorsque notre autolicker va acheter de nouvelles compétences pour nos
personnages, on va d'abord cliquer sur l'onglet de ce personnage, afin de
pouvoir visualiser les compétences qu'on achète. D'abord, c'est plus sympa, mais
surtout ça nous permet de voir facilement si notre code fonctionne !

Aussi, quand il n'y a rien de disponible à acheter, on affichera le jeu plutôt
que de rester sur le dernier onglet utilisé.

Malheureusement, les `<a />` qui constituent ces onglets n'ont pas d'attribut
`id` ou `class` individuels pour les sélectionner facilement. Il faut donc lire
leur contenu (le texte du bouton) pour savoir à quoi correspond notre onglet.

On parcourt donc les onglets dans une boucle. Pour ceux qui nous intéressent,
c'est à dire l'onglet « Game » permettant d'afficher le jeu, et les feuilles de
personnages, on stocke une référence vers la fonction de clic.

Les onglets personnages affichent un nombre quand le personnage dispose de
points de compétences. Par exemple, l'onglet du rogue contiendra `'Rogue 5'`
dans ce cas, et simplement `'Rogue'` si aucun point de compétences n'est
disponible. Par conséquent on utilise une expression régulière pour trouver
notre onglet. Cela nous permet également de stocker une fonction renvoyant le
nombre de points de compétences disponibles pour notre personnage, que l'on
utilisera plus tard pour décider si on doit aller acheter ces points.

[source,javascript]
----
var tabs = document.querySelectorAll('.__TABS_WRAPPER_CLASS a')
  .reduce(function(tabs, a) {
    if (a.innerHTML === 'Game') {
      tabs.game = return {type: 'game', click: a.onclick}
    } else if (a.innerHTML.match(/(Pyro|Druid|Rogue|King|__TODO__)( [0-9]+)?/)) {
      tabs.characters.push({
        click: a.onclick,
        skillpoints: function() {
          var match = a.innerHTML.match(/([0-9]+)/)
          return match ? Number(match[0]) : 0
        }
      })
    }
    return tabs
  }, {characters: []})
----

=== Acheter des compétences

On sait maintenant afficher les feuilles de personnages en cliquant sur ces
onglets. Reste à interagir avec.

Commençons par établir un lien entre nos onglets `characters` et les tableaux
de compétences disponibles en jeu. L'onglet « Skills » est affiché par défaut
donc on ne va pas rajouter une étape de clic dessus.

== @todo
skills utilisent mouseup()
Attente du chargement
Récupération des liens & boutons
Lecture des points de compétence disponibles
Orchestration
