---
title: "Comment jouer encore moins dans un incremental-game"
date: 2017-01-31
tags: [javascript, incremental-games]
---

La triche c'est mal m'voyez ? Mais voici quand même un petit script permettant
de créer facilement des _autoclicker_ via la console du navigateur.

++++
<!-- more -->
++++

== Les incremental games

Vous connaissez sûrement le principe de _incremental games_, mais un petit
rappel ne coûte pas cher. (Sinon sautez directement au titre suivant !)

Il s'agît de jeux ou le but principal est d'« augmenter ». En général on
augmente un simple nombre comme une réserve d'argent, de ressources, mais il
faut parfois augmenter plusieurs types de ressources.

En général, le système de jeu se développe également au fil du jeu, en
augmentant le nombre d'éléments de l'interface ou d'actions possibles.

Voici quelques exemples que je trouve sympathiques :

- http://jhollands.co.uk/spaceplan/[SPACEPLAN]
- http://minmaxia.com/c2/[CLICKPOCALYPSE 2]
- https://trimps.github.io/[Trimps]
- http://cirri.al/sharks/[Shark Game: Shark of Darkness]
- http://candies.aniwey.net/[Candy box !]
- https://swarmsim.github.io/[Swarm Simulator]

Si vous lisez ceci, c'est que vous avez réussi à vous extirper de ces jeux,
bravo ! Moi ça me prend beaucoup trop de temps malheureusement.

== Les clickers

Les mécaniques d'un incremental ne sont pas toujours intéressantes. Celles de
Swarm Simulator sont très répétitives par exemple, la seule évolution consiste à
changer d'unité : passer de 1^12^ à 1^13^ par exemple. En contrepartie, ces jeux
prennent peu de temps et continuent généralement d'évoluer hors ligne, quand on
ne s'en occupe pas.

Mais il y a une catégorie d'_incremental games_ pire que les autres : les
_clickers_. Dans un clicker, la mécanique principale consiste à cliquer sur un
bouton pour gagner des ressources ou faire évoluer un simple nombre. Or il ne
s'agît généralement pas d'un choix intéressant comme choisir une nouvelle
technologie à développer, ou bien installer plutôt un générateur d'oxygène
supplémentaire ou réparer le filtre à eau avec les maigres ressources disponible
dans notre station spatiale en ruine. Non, on clique pour ajouter `1` à notre
ressource.

De plus, ces jeux sont généralement lents, demandant de cliquer de très, très
nombreuses fois au même endroit. Un genre de musculation de l'index quoi.
Pauvres de vous si vous y jouez avec un _trackpad_ !

Pour ces jeux, aucune pitié, l'utilisation d'un autoclicker est o-bli-ga-toire
afin de profiter des maigres évolutions de gameplay et du scénario (s'il
existe).

== Autoclicker

Pour les jeux plus sympathiques comme Trimps ou Clickpocalypse, les autoclicker
permettent de rendre le jeu presque totalement _idle_. Pourquoi faire ?

Disons que les éléments sur lesquels on doit cliquer représentent parfois des
choix évidents. Par exemple, dans Clickpocalypse, la barre de gauche contient
les récompenses et les loot des donjons que l'on farme. Cliquer dessus permet de
récupérer ces récompenses et ne-pas cliquer dessus n'a aucun intérêt (mis à part
les boutons « Attack Castle » qu'il faudra tâcher d'ignorer).

Autre exemple, les boutons permettant d'utiliser les parchemins sont désactivés
quand il n'y a pas d'ennemis. Le clic n'est donc possible que quand le parchemin
est utile (un ennemi est présent). C'est donc une bonne idée de mettre un
_autoclicker_ dessus.

=== Version synchrone

Un _autoclicker_ fonctionne est une boucle qui va exécuter `n` fois la même
fonction, généralement sélectionner un bouton à cliquer, et lancer le clic.

Voici donc une fonction qui permet de créer une telle boucle :

[source,javascript]
----
function looper(callback) {
  return function loop(x, i) {
    for (i = 0; i < x; i++) {
      callback(i)
    }
  }
}
----

Et voici comment on s'en sert :

[source,javascript]
----
var loop = looper(function(n){
  // Ici on implémentera les clics
  console.log("Boucle n°%s", n)
})

loop(10) // on lance la boucle 10 fois
----

Malheureusement, cette version synchrone pose une problème majeur : durant
l'exécution, le navigateur est « freezé », et l'exécution du script fait tourner
le processeur de votre PC (ou l'un de ses coeurs) à 100%. Certains navigateurs
que je ne nommerai pas ne permettront même pas qu'on ferme ou recharge la page,
et il faudra les fermer de force.

Impossible donc de lancer une boucle 10 000 fois tout en continuant de jouer,
d'autant plus si le jeu exécute lui-même de nombreuses opérations lors d'un
unique clic. Et c'est le but, on ne fait pas tout ça pour des clics qui ne font
rien !

=== Version Asynchrone

Voici une version asynchrone qui relègue chaque itération de la boucle à
l'itération suivante du gestionnaire d'évènements du moteur Javascript. Le
navigateur se comportera normalement et la boucle agira comme une sorte de tâche
de fond.

Le temps entre chaque itération sera beaucoup plus long, et ne
pourra de toutes façons pas être inférieur à
https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setTimeout#Reasons_for_delays_longer_than_specified[4 millisecondes].

Ce n'est généralement pas un problème, et en contrepartie on peut lancer la
boucle à l'infini (et au delà) !

Vous pouvez l'essayer dans la console sans crainte. Pour l'arrêter il suffit de
recharger la page.

[source,javascript]
----
looper.async = function(callback, timeout) {
  timeout = timeout || 1
  return function loop(x, i) {
    i = i || 0
    if (i < x){
      setTimeout(function(){
        callback(i)
        loop(x, i + 1)
      }, timeout)
    }
  }
}

var loop = looper.async(function(n){
  console.log("Boucle n°%s", n)
})

// N'ayons pas peur et lançons la boucle
// au delà de l'infini :)
loop(Infinity + 1)
----

++++
<script>

function looper(callback) {
  return function loop(x, i) {
    for (i = 0; i < x; i++) {
      callback(i)
    }
  }
}

looper.async = function(callback, timeout) {
  timeout = timeout || 1
  return function loop(x, i) {
    i = i || 0
    if (i < x){
      setTimeout(function(){
        callback(i)
        loop(x, i + 1)
      }, timeout)
    }
  }
}

console.log("Hello !")
console.log("Le looper est déjà défini dans la console,")
console.log("mais n'hésitez pas à redéfinir la variable")
console.log("avec les exemples de l'article.")

</script>
++++
