---
title: "Génération procédurale de cartes réalistes"
date: 2017-01-24
draft: true
// user_scripts: ['https://d3js.org/d3.v4.min.js', 'js/mapgen/maptest.js']
---

Pour la création d'un petit jeu incrémental sur lequel je travaille en
ce moment, basé sur des tuiles hexagonales, j'avais envie d'afficher
au joueur une carte assez élaborée respectant ces critères :

- La carte doit être générée de façon procédurale à partir d'une
  graine (_seed_ en Anglais), c'est à dire un simple nombre aléatoire,
  afin d'avoir une carte différente à chaque partie ;
- La carte générée à partir d'un même nombre doit toujours être la
  même, parce-que je ne la sauvegarde pas avec le jeu, je la régénère
  au chargement du jeu, seule la _seed_ est sauvegardée.
- La zone de jeu doit être suffisament étendue : le nombre de tuiles disponibles
  au joueur doit être suffisant pour le gameplay.
- La carte doit répondre à certains élements de _level-design_ : on doit
  retrouver les mêmes élements sur toutes les cartes : zones basses, montagnes,
  déserts, etc.

Les tutoriels suivant m'ont beaucoup aidé :

- Gestion des coordonnlocaées (@todo lien) ;
- Génération de map procédurale (@todo lien) ;

Je vous conseille vivement laa lecture du dernier qui est très complet ! Mon
article est surtout là pour montrer comment j'ai choisi de répondre à chaque
contrainte que je me suis imposée.

== Génération procédurale à partir d'une graine
