wget -nc "https://fonts.gstatic.com/s/merriweather/v13/RFda8w1V0eDZheqfcyQ4EK-j2U0lmluP9RWlSytm3ho.woff2" --no-check-certificate
wget -nc "https://fonts.gstatic.com/s/merriweather/v13/RFda8w1V0eDZheqfcyQ4EJX5f-9o1vgP2EXwfjgl7AY.woff2" --no-check-certificate
wget -nc "https://fonts.gstatic.com/s/merriweather/v13/RFda8w1V0eDZheqfcyQ4ED0LW-43aMEzIO6XUTLjad8.woff2" --no-check-certificate
wget -nc "https://fonts.gstatic.com/s/merriweather/v13/RFda8w1V0eDZheqfcyQ4EOgdm0LZdjqr5-oayXSOefg.woff2" --no-check-certificate
wget -nc "https://fonts.gstatic.com/s/merriweather/v13/ZvcMqxEwPfh2qDWBPxn6nrPaLDTSXeXFRL0dx0NiHII.woff2" --no-check-certificate
wget -nc "https://fonts.gstatic.com/s/merriweather/v13/ZvcMqxEwPfh2qDWBPxn6ntkZ6ofoXFVR94fBb90XSvU.woff2" --no-check-certificate
wget -nc "https://fonts.gstatic.com/s/merriweather/v13/ZvcMqxEwPfh2qDWBPxn6nuIaMZP5eRGvEWe_CNIU_oY.woff2" --no-check-certificate
wget -nc "https://fonts.gstatic.com/s/merriweather/v13/ZvcMqxEwPfh2qDWBPxn6nnNuWYKPzoeKl5tYj8yhly0.woff2" --no-check-certificate
wget -nc "https://fonts.gstatic.com/s/merriweather/v13/So5lHxHT37p2SS4-t60SlJX7FfjVuZf3W7tKvrYzIk8.woff2" --no-check-certificate
wget -nc "https://fonts.gstatic.com/s/merriweather/v13/So5lHxHT37p2SS4-t60SlOb988d5RHZc66psPc8fYGQ.woff2" --no-check-certificate
wget -nc "https://fonts.gstatic.com/s/merriweather/v13/So5lHxHT37p2SS4-t60SlMAbIeegqMtwkwn2ZHUR4Nk.woff2" --no-check-certificate
wget -nc "https://fonts.gstatic.com/s/merriweather/v13/So5lHxHT37p2SS4-t60SlBMBlNeli-0RcAdOFWWLdxQ.woff2" --no-check-certificate
wget -nc "https://fonts.gstatic.com/s/merriweather/v13/EYh7Vl4ywhowqULgRdYwIEVUTRPtBn3BSc_rW_ryx7U.woff2" --no-check-certificate
wget -nc "https://fonts.gstatic.com/s/merriweather/v13/EYh7Vl4ywhowqULgRdYwIDaggPqPUlqZtH2DnDrcMQE.woff2" --no-check-certificate
wget -nc "https://fonts.gstatic.com/s/merriweather/v13/EYh7Vl4ywhowqULgRdYwIOR3LJ09PnibSpWhv21tZ8w.woff2" --no-check-certificate
wget -nc "https://fonts.gstatic.com/s/merriweather/v13/EYh7Vl4ywhowqULgRdYwIEcqRxak6Wc5LUVz-l064SE.woff2" --no-check-certificate
