source "https://rubygems.org"

# Make sure Jekyll 3.3 is running
gem "jekyll", "3.5.1"

# The theme for the site
gem "alembic-jekyll-theme", "~> 2.1"

# The plugins for the site
group :jekyll_plugins do
  gem "jekyll-sitemap"
  gem "jekyll-mentions"
  gem "jekyll-paginate"
  gem "jekyll-seo-tag"
  gem "jekyll-redirect-from"
  gem "jekyll-feed"
  gem "jemoji"
  gem 'jekyll-asciidoc'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

gem "pygments.rb", "~> 1.1.2"
