# Header
menu:
  "RSS": /feed.xml

# Content
excerpt_link: Lire la suite

widgets:

# Links
links:

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:

